@api = http://localhost:3000/level

GET {{api}}


###

# PUT {{api}}/73
# Content-Type: application/json

# {
#     "level": "74",
#     "Exp": "550977453"
# }


###


DELETE {{api}}/73

###


GET {{api}}/73

###

POST {{api}}
Content-Type: application/json

{
    "level": "73",
    "Exp": "550977453"
}

